# Site settings
title: Prakruti Catherine Gogia
description: 'Computer Vision and Machine Learning Enthusiast'
url: 'https://prakruti.github.io/'
baseurl: '/'
# google_analytics: 'UA-XXXXXX-X'
# disqus_shortname: 'your-disqus-name'

author:
  name: 'Prakruti Catherine Gogia'
  email: pgogia@andrew.cmu.edu
  facebook_username: pgogia
  github_username:  prakruti
  linkedin_username: prakruti-catherine-gogia-0a371a51?trk=hp-identity-name

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: none
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
